language: node_js

node_js:
    # Maintenance
    - "6"
    # Production
    - "8"
    # Next LTS
    - "10"
    # From the nvm docs, "this installs the latest version of node".
    - "node"

# FIXME: Node.js v11.x introduced a difference with how timers are run that
# results in some about ids in blacklisted tests being off.  Needs
# investigation but, regardless, should be fixed by T206222
# See https://github.com/nodejs/node/pull/22842
matrix:
  allow_failures:
  - node_js: "node"

before_install:
    - npm i -g npm@3

install:
    - npm i --no-optional

script: travis_wait npm run-script coverage

after_success: npm run-script coveralls

notifications:
  email:
    - secure: "UPDzE/JcwvnoewrGVuuVrX0TFz2Q5PYkS2xxA45FRiCPvc2KxVvC9YX0xOKklm6iiiyH95lKRgAD8D53gg1tJmpR2+Z2BAfvfyy41MDB9P5ufwn9NoulmrLFLWCQxf+fqmT1qjyle4pql44y8nN7PCejn1Zkz4pko29bz0c3Blg="
